### ISSUE TITLE
previous/next wizard path not working with skip_step

### ISSUE THREAD

**Issue by yshmarov** [zombocom/wicked#265]
**Current behavior:**
`previous_wizard_path `and `next_wizard_path `do not work if `skip_step `is triggered on previous/next step.
**Desired behavior:**
`previous_wizard_path `and `next_wizard_path ` redirect to previous/next step that is not skipped.

**Comment by schneems** [comment]
I would take a PR on this if someone wants to take a stab at it. It would help to have an example app that demonstrates the problem.

codetriage.com/example_app

**Comment by kaelumania** [comment]
@yshmarov maybe you can use dynamic_steps to work around this.

**Comment by schneems** [comment]
I never got a reproduction. Closing this.
