### ISSUE TITLE
Return 422 (unprocessable entity) when form submissions fails

### ISSUE THREAD

**Issue by marckohlbrugge** [zombocom/wicked#278]
Hotwire Turbo (formerly known as Turbolinks) [requires a failed POST request to return a `422` response](https://turbo.hotwire.dev/handbook/drive#redirecting-after-a-form-submission) (`unprocessable entity`). Wicked currently returns a `200` (`ok`) response which makes it incompatible with Turbo.

In the past a PR ( https://github.com/zombocom/wicked/pull/267 ) was created to change the status to `unprocessable entity` but this was rejected in order to stick to Rails' own defaults.

These defaults in Rails [have now changed to also use `422`](https://github.com/rails/rails/pull/41026) for failed POST requests. So I'd like to request Wicked to be updated to do the same.

[The existing PR](https://github.com/zombocom/wicked/pull/267) seems like a good solution.

**Comment by deepakmahakale** [comment]
Sounds good 
But we may need to rebase the PR.
