### ISSUE TITLE
the gem died?

### ISSUE THREAD

**Issue by ismarsantos** [zombocom/wicked#280]
the gem died? is there any fork or alternative to rails 6.1 and rails 7?

in the scenario below with dynamic steps, when I add this way I get the following error message:

``No step definitions have been supplied; if setting via `before_action`, use ``prepend_before_action`"`

``
include Wicked::Wizard
``
``
before_action :set_steps
``
``
before_action :setup_wizard
``
# ...

private
def set_steps
  if params[:flow] == "twitter"
    self.steps = [:ask_twitter, :ask_email]
  elsif params[:flow] == "facebook"
    self.steps = [:ask_facebook, :ask_email]
  end
end

**Comment by jnicho02** [comment]
I'm happily using the wizard with Rail 6.1.4

You will see this error message if steps==nil, so I bet you any money that in your set_steps that params[:flow] is neither 'twitter' nor 'facebook' and hence you aren't setting any steps
