### ISSUE TITLE
The requested step did not match any steps defined for this controller: "add_height"

### ISSUE THREAD

**Issue by bugdimes** [zombocom/wicked#295]
Hi, I have defined dynamic steps based on the previous step

This is how my controller looks like
```
class Entrys::BuildController < ApplicationController
    include Wicked::Wizard
    before_action :set_steps
    before_action :setup_wizard
    ...
```

```
...
private
def set_steps
        if params[:entry] && params[:entry]['preference_height_or_wight'] == "height"
            self.steps = [:add_name, :add_email, :add_preference, :add_height]
        else
            self.steps = [:add_name, :add_email, :add_preference, :add_weight]
        end
end
```

There is a view present called add_height.html.erb and weight, but for the if condition is returns the above mentioned error

**Comment by jnicho02** [comment]
Looks okay at first glance. Are you sure that the if-statement that looks at params is correct? E.g. 'preference_height_or_wight'?

**Comment by fitterfly-divyesh** [comment]
Hi, Yes, 
So in `add_preference` step, There is a form with one question which asks what you wanna enter next, Height or Weight
If you select height then I need to show height form or vice versa.

`preference_height_or_wight` is the Entry model's field which is enum
@jnicho02

**Comment by fitterfly-divyesh** [comment]
Hi @jnicho02 , I did something like below and it worked
I am not 100% sure

```ruby
...
private
def set_steps
        if params[:entry] && params[:entry]['preference_height_or_wight'] == "height"
            self.steps = [:add_preference, :add_height] # Here I removed earlier steps
        else
            self.steps = [:add_preference, :add_weight] # Here I removed earlier steps
        end
end
```
